open-api:
  #是否热读取xml配置，生产环境不要开启此功能
  hotReadXml: true
  enableCache: true
  enableApiDoc: true
  ipWhite:
    - 127.0.0.1
    - 192.168.1.1
#  cacheHandlerPath: xyz.erupt.aa
spring:
  datasource:
    url: jdbc:h2:mem:test_db
    driverClassName: org.h2.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  port: 8891