openApi:
  #是否热读取xml配置，生产环境不要开启此功能
  hotReadXml: true
  openCache: true
  #  cacheProvider: xyz.erupt.aa
  apiDoc: true
spring:
  datasource:
    url: jdbc:mysql://39.104.174.237:3306/wisdom-community-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: E3&$cBW#
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8891