openApi:
  #是否热读取xml配置，生产环境不要开启此功能
  hotReadXml: true
  openCache: true
  #  cacheProvider: xyz.erupt.aa
open-doc:
  enable: true
#  ipWhite:
#    - 127.0.0.1
#    - 192.168.1.1
spring:
  datasource:
    url: jdbc:mysql://39.104.174.237:3306/erupt?useUnicode=true&characterEncoding=UTF-8
    username: erupt
    password: leLPvYbQQ!27st2FuxtO
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8891