#jdbc
spring:
  datasource:
    url: jdbc:sqlserver://59.110.40.167:3434;DatabaseName=erupt
    username: sa
    password: msSQL2017
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    hibernate:
      ddl-auto: update
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    timeout: 10000
server:
  port: 9999
  compression:
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    enabled: true